### ISSUE TITLE
cordova-android 7.x.x not supported

### ISSUE THREAD

**Issue by bytenik** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#24]
The androidManifest.xml file has moved as part of support for Android Studio projects. The following error I receive on installation indicates your plugin doesn't support cordova-android 7.

```C:\Users\bytenik\Dropbox\Projects\BallStreet\app>cordova plugin add cordova-plugin-appsflyer-sdk
Installing "cordova-plugin-appsflyer-sdk" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-appsflyer-sdk': Error: Uh oh!
ENOENT: no such file or directory, open 'C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.parseElementtreeSync (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at AndroidProject.getCustomSubprojectRelativeDir (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\lib\AndroidProject.js:105:28)
    at install (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\lib\pluginHandlers.js:106:46)
    at ActionStack.process (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
Error: Uh oh!
ENOENT: no such file or directory, open 'C:\Users\bytenik\Dropbox\Projects\BallStreet\app\platforms\android\AndroidManifest.xml'```

**Comment by bytenik** [comment]
Please also see: http://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

**Comment by LucyHeres** [comment]
are you solve that?

**Comment by jacquesdev** [comment]
I believe this was fixed here:
https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/commit/f5008de9f0474d0581af3063b10ecfa11528905c
