### ISSUE TITLE
java.lang.ClassNotFoundException: com.appsflyer.cordova.plugin.AppsFlyerPlugin

### ISSUE THREAD

**Issue by kazyumaru** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#38]
Tomcat says

java.lang.ClassNotFoundException: com.appsflyer.cordova.plugin.AppsFlyerPlugin
06-03 09:00:40.099 15390-15798/io.ionic.starter W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appsflyer.cordova.plugin.AppsFlyerPlugin" on path: DexPathList[[zip file "/data/app/io.ionic.starter-1/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.starter-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-03 09:00:40.099 15390-15798/io.ionic.starter I/System.out: Error adding plugin com.appsflyer.cordova.plugin.AppsFlyerPlugin.

I use this sdk with Ionic 3.
And I tried to test on a real device ( Android 7.0).

I think this is PATH error but I cannot detect where is wrong.

Thanks.

**Comment by af-fess** [comment]
@kazyumaru please give info about your enviroment, what is the version of android platform?

**Comment by dilanfdo** [comment]
I am facing the same issue. Is this sloved? Below i have mentioned the error im getting.

07-18 19:29:35.001 27383-27575/com.cardofjoy.userapp E/art: ClassLinker::FindClass not found:Lcom/appsflyer/cordova/plugin/AppsFlyerPlugin;
07-18 19:29:35.002 27383-27575/com.cardofjoy.userapp W/System.err: java.lang.ClassNotFoundException: com.appsflyer.cordova.plugin.AppsFlyerPlugin
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:309)
        at java.lang.Class.forName(Class.java:273)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appsflyer.cordova.plugin.AppsFlyerPlugin" on path: DexPathList[[zip file "/data/app/com.cardofjoy.userapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cardofjoy.userapp-1/lib/arm, /vendor/lib, /system/lib]]
07-18 19:29:35.003 27383-27575/com.cardofjoy.userapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    	... 13 more
    	Suppressed: java.lang.ClassNotFoundException: com.appsflyer.cordova.plugin.AppsFlyerPlugin
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 14 more
    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-18 19:29:35.003 27383-27575/com.cardofjoy.userapp I/System.out: Error adding plugin com.appsflyer.cordova.plugin.AppsFlyerPlugin.
