### ISSUE TITLE
Failed to install 'cordova-plugin-appsflyer-sdk': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!

### ISSUE THREAD

**Issue by Gamaroff** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#50]
Unable to install plugin.

Specs and install output as follows.

```
Ionic:

   ionic (Ionic CLI)  : 4.3.1 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.1.2 
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (23 plugins total)

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 2.0.0
   NodeJS            : v11.1.0
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```
```
$ ionic cordova plugin add cordova-plugin-appsflyer-sdk
> cordova plugin add cordova-plugin-appsflyer-sdk --save
Installing "cordova-plugin-appsflyer-sdk" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-appsflyer-sdk': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
   
Uh oh!
The "path" argument must be of type string. Received type undefined
```

**Comment by Michael-Francalanci** [comment]
Same here.

**Comment by paulstelzer** [comment]
This problem seems to be an issue with `cordova-android@7.1.2`. I have the same at another plugin. Reverting back to  `cordova-android@7.1.1` works

**Comment by BenjaminAF** [comment]
Issue was resolved and merged.
https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/tree/dev/RD-17185/Android7.1.0Path_fix
If this is still happening for anyone with the new version please let us know.
